Just Codes
jarun/keysniffer pull request #4
Opened 2017-03-20 02:20 UTC by dvad924

Log only codes for flexibility #3 

I added shift masks as well figure it might make parsing combos easier.

2017-03-20 02:44 UTC, jarun commented on keysniffer.c
> +  for ( i = 0; i < size; i++)
Extra space between `( and i`.

2017-03-20 02:44 UTC, jarun commented on keysniffer.c
> +  if( !input ){
There should be a space between `if and (`

2017-03-20 02:46 UTC, jarun commented
Please follow the kernel coding guideline:

https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst

The basics should cover. If that seem time-consuming, just refer to a random file, e.g.

https://github.com/torvalds/linux/blob/master/crypto/ablk_helper.c

2017-03-20 15:27 UTC, dvad924 commented
Thanks for the reference!
I will get on that, should be fixed soon.

2017-03-20 20:29 UTC, jarun requested changes

2017-03-20 20:29 UTC, jarun commented on keysniffer.c
> +void to_base_n_string(int input, int n,char *rep,int size){
Please add spaces between `int n,char *rep,int size)`
The `{` should be on the next line.

2017-03-20 20:29 UTC, jarun commented on keysniffer.c
> +	while ( div > 0 ) {
No extra spaces after `(` and before `)`.

2017-03-20 20:29 UTC, jarun commented on keysniffer.c
> +	for (i = start; i < size; i++) {
You can drop `{` and `}` for single liners.

2017-03-20 20:29 UTC, jarun commented on keysniffer.c
> +			if ( codes ) {
No extra spaces after `(` and before `)`.

2017-03-20 20:29 UTC, jarun commented on keysniffer.c
> +			if( codes ) {
Space after `if`.

2017-03-20 20:36 UTC, jarun requested changes

2017-03-20 20:36 UTC, jarun commented on keysniffer.c
> +			if ( codes ) {
No extra spaces after `(` and before `)`.

2017-03-20 20:36 UTC, jarun commented on keysniffer.c
> +			} else {
You can drop `{` and `}` for single liners.

2017-03-20 20:36 UTC, jarun commented on keysniffer.c
> +				to_base_n_string(param->value,10,key,sizeof(int)+1);
`(param->value,10,key,sizeof(int)+1)`

should be

`(param->value, 10, key, sizeof(int) + 1)`

2017-03-20 20:36 UTC, jarun commented on keysniffer.c
> +				to_base_n_string(param->shift,10,rep,sizeof(int)+1);
`(param->shift,10,rep,sizeof(int)+1)`

should be

`(param->shift, 10, rep, sizeof(int) + 1)`

2017-03-20 20:36 UTC, jarun commented on keysniffer.c
> +				strncpy(keys_buf + buf_pos, pressed_key,
It's OK to bring the last param in the same line instead of the next line.

2017-03-20 20:38 UTC, jarun commented
I have reviewed as much as possible. But more violations are possible given you are apparently writing kernel module code for the first time. Please use [checkpatch](http://tuxdiary.com/2015/03/22/check-kernel-code-checkpatch/) to fix the remaining defects. Before accepting the PR, I'll verify against it too.

2017-03-21 14:35 UTC, dvad924 commented
Thanks for all the feedback!
Yes this is my first module.
I apologize for not adhering strictly before, I thought I hit the major points but didn't realize how important the formatting is to the code. I used the checkpatch.pl script and removed all the errors.
(there are still warnings for lines over 80chars and not using the "const" keyword)

2017-03-21 14:38 UTC, jarun requested changes

2017-03-21 14:38 UTC, jarun commented on keysniffer.c
> +
Redundant blank line?

2017-03-21 14:38 UTC, jarun commented on keysniffer.c
> +
Redundant newline.

2017-03-21 14:38 UTC, jarun commented on keysniffer.c
> +
extra blank line

2017-03-21 14:44 UTC, jarun commented
I also need a **detailed explanation** of what you are trying to do in the code, usually something like an elaborate commit message. For example, how you are encoding the keypresses, how you are decoding them when read from debugfs etc.

I would appreciate if you realize the fact that PRs without any description of how it is achieving something seems meaningless to people who would be reviewing them.

2017-03-22 00:42 UTC, jarun commented
I wasn't referring to cod comments... A commit description as a whole. For example, take a look at this PR: https://github.com/jarun/Buku/pull/128

Here the contributor has explained in complete detail what he is trying to do and how he is doing it. I need something at this level to *start* reviewing the logic in the code.

2017-03-22 02:43 UTC, dvad924 commented
- Feature Description
     Add option to log the raw keycodes instead of the US keyboard characters

- Design Changes
     An optional integer parameter can be passed at time of inserting the module 
     to log raw codes. Ex : `sudo insmod kisni.ko codes=1` If the parameter is not included
     the module will default to logging US characters. Using this option will result in the log file
     having each line formatted as "shiftmask_space_keycode" where shiftmask and keycode 
     are the base 10 representational strings of the values received. The shiftmask was added for 
     use in finding key combinations.

     Integer module parameter added.
     String values are written to the same buffer in the same way as the original implementation.

2017-03-22 03:25 UTC, jarun commented on README.md
> +    4 30
What is 4? As per my understanding, this is shift_mask and can be 0 or 1 right?

2017-03-22 03:25 UTC, jarun commented on EX.txt
> +1 52
What is this new file EX.txt?

2017-03-22 03:25 UTC, jarun commented on keysniffer.c
>  	if (param->value >= 0x1 && param->value <= 0x77) {
If you want to show any value, why do you put your logic within this condition?

2017-03-22 03:25 UTC, jarun commented on keysniffer.c
> +	int max_len = sizeof(int) + 1;
Will it be possible to capture Unicode? Also can we show the values in hex rather than in decimal? We can omit the 0x prefix in all cases.

2017-03-22 04:19 UTC, dvad924 commented on README.md
> +    4 30
Originally I thought so as well, but per testing it seems to capture Shift,Ctrl,Alt possibly more, haven't found docs on it yet, keyboard.h doesn't have any insights. It is a proper bitmask it seems.

2017-03-22 04:21 UTC, dvad924 commented on EX.txt
> +1 52
This was an example I included before adding to the readme, I will remove it.

2017-03-22 04:22 UTC, jarun commented
Note: If it's possible to fetch the max and min scancode from the keyboard driver, our life would be easy to limit the buffer size required to hold a scancode.

2017-03-22 04:30 UTC, dvad924 commented on keysniffer.c
>  	if (param->value >= 0x1 && param->value <= 0x77) {
This was done with the intent of restricting the characters logged to the same as was done originally. If we want any & all codes that is great and should be done in a more modular function that could deal with a number of different parameters and options

2017-03-22 04:37 UTC, dvad924 commented on keysniffer.c
> +	int max_len = sizeof(int) + 1;
Hex is fine, Unicode I will need to look into ...

2017-03-22 04:40 UTC, jarun commented
How about the following (though it does not break out of the 0x1 to 0x77 limit yet):

```
diff --git a/keysniffer.c b/keysniffer.c
index 0fec77a..4138d15 100644
--- a/keysniffer.c
+++ b/keysniffer.c
@@ -21,16 +21,23 @@
 #include <linux/init.h>
 #include <linux/kernel.h>
 #include <linux/module.h>
+#include <linux/moduleparam.h>
 #include <linux/keyboard.h>
 #include <linux/debugfs.h>
 
 #define BUF_LEN (PAGE_SIZE << 2) /* 16KB buffer (assuming 4KB PAGE_SIZE) */
 
+#define MAX_ENC_LEN 12           /* Length of an encoded 'code shift' chunk */
+static int codes;                /* Log type module parameter */
+
 MODULE_LICENSE("GPL v2");
 MODULE_AUTHOR("Arun Prakash Jana <engineerarun@gmail.com>");
 MODULE_VERSION("1.4");
 MODULE_DESCRIPTION("Sniff and log keys pressed in the system to debugfs");
 
+module_param(codes, int, 0644);
+MODULE_PARM_DESC(codes, "Flag: 0: US keyboard, 1: keycodes (base10)");
+
 /* Declarations */
 static struct dentry *file;
 static struct dentry *subdir;
@@ -104,24 +111,34 @@ static struct notifier_block keysniffer_blk = {
 
 /* Keypress callback */
 int keysniffer_cb(struct notifier_block *nblock,
-		unsigned long code,
-		void *_param)
+		  unsigned long code,
+		  void *_param)
 {
 	size_t len;
+	char code_buf[MAX_ENC_LEN] = {0};
 	struct keyboard_notifier_param *param = _param;
 	const char *pressed_key;
 
 	pr_debug("code: 0x%lx, down: 0x%x, shift: 0x%x, value: 0x%x\n",
-		code, param->down, param->shift, param->value);
+		 code, param->down, param->shift, param->value);
 
 	if (!(param->down))
 		return NOTIFY_OK;
 
 	if (param->value >= 0x1 && param->value <= 0x77) {
 		pressed_key = param->shift
-				? us_keymap[param->value][1]
-				: us_keymap[param->value][0];
+			? us_keymap[param->value][1]
+			: us_keymap[param->value][0];
 		if (pressed_key) {
+			if (codes) {
+				sprintf(code_buf, "%x ", param->value);
+                                if (param->shift)
+                                    strncat(code_buf, "1", MAX_ENC_LEN);
+                                else
+                                    strncat(code_buf, "0", MAX_ENC_LEN);
+				pressed_key = code_buf;
+			}
+
 			len = strlen(pressed_key);
 
 			if ((buf_pos + len) >= BUF_LEN) {
```

2017-03-22 04:51 UTC, jarun commented on README.md
> +    4 30
Strange indeed. Thanks! We should show these values.

2017-03-22 04:52 UTC, jarun commented on EX.txt
> +1 52
Thanks!

2017-03-22 04:52 UTC, jarun commented on keysniffer.c
> +	int max_len = sizeof(int) + 1;
Sure, it would be a great value addition.

2017-03-22 04:54 UTC, jarun commented on keysniffer.c
>  	if (param->value >= 0x1 && param->value <= 0x77) {
Maybe we just need to put our new login in an else. It'll surely remain distinct.

2017-03-23 02:20 UTC, jarun requested changes

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +1;2802;0c * A Linux kernel module to grab keycodes and log to debugfs
What's this? ;)

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +#define SHIFT 1                       /* shift_mask code for shift */
We are not using this. Please remove.

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +  case OCT:
We don't need octal. Please remove.

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +  case UNI:
As of now it is same as HEX and probably we need to handle Unicode differently. Please remove.

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +MODULE_PARM_DESC(codes, "Flag: 0: US keyboard, 1: keycodes (base16) 2: (base10) 3: (base8)");
Please mention 0 as default, i.e.:

`Flag: 0: US keyboard (default)`

Also, please drop octal.

2017-03-23 02:20 UTC, jarun commented on keysniffer.c
> +      snprintf(buffer, MAX_ENC_LEN, "%s %x", pressed_key, shift_mask);
Nice! I forgot snprintf() can handle multiple args! :+1:

2017-03-23 02:26 UTC, jarun commented
The last commit is very close and quite clean. We're almost there. :+1:

2017-03-26 15:54 UTC, merged

2017-03-26 15:55 UTC, jarun commented
It's been a long time. I'll take care of the comments myself.

2017-03-26 17:16 UTC, jarun commented
The indentation, coding style (tabs converted into spaces or just new spaces) is broken in every function this PR touches. Reverting.

2017-03-28 04:22 UTC, dvad924 commented
Thanks for finishing it and sorry I wasn't able to get to in the past few days, had other things going on.

2017-03-28 04:24 UTC, jarun commented
No problem!