Save output to other file in the VFS
jarun/keysniffer pull request #6
Opened 2017-04-18 19:34 UTC by cedriczirtacic

Added parameter output_path to the module so you can save the output of keys pressed on another specified file in the filesystem.

2017-04-18 22:53 UTC, jarun commented
Please run the patch against [checkpatch](http://tuxdiary.com/2015/03/22/check-kernel-code-checkpatch/) and fix the issues.

2017-04-18 23:22 UTC, jarun requested changes

2017-04-18 23:22 UTC, jarun commented on keysniffer.c
> +	} else{
should be

`} else {`

2017-04-18 23:24 UTC, jarun commented
Also, please document it under the **Usage** section in README. What use would it be do you think if only you and me know about it? :)

2017-04-18 23:31 UTC, cedriczirtacic commented
You're right, jarun. Gonna take a moment and modify the README.md
Thanks!

2017-04-18 23:31 UTC, jarun commented
Thank you!

2017-04-18 23:32 UTC, jarun commented
BTW, I know people looking for this feature. It adds good value. :+1:

2017-04-18 23:41 UTC, cedriczirtacic commented
Thanks, jarun! I was also looking for something like that so I decided to help.

2017-04-18 23:44 UTC, merged

2017-04-18 23:44 UTC, jarun commented
Thank you for your contribution!

2017-04-18 23:46 UTC, jarun commented on keysniffer.c
> +		loff_t off = 0;
There's a warning in this line:

```
/home/vaio/GitHub/keysniffer/keysniffer.c:189:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   loff_t off = 0;
```

2017-04-18 23:48 UTC, jarun commented on keysniffer.c
> +		loff_t off = 0;
Leave, it. I'll take care of it. Need to make another change anyway.

2017-04-19 00:01 UTC, jarun commented
**Regression:**

On my system as soon as I run:

`sudo insmod kisni.ko output_path=/home/user/keys`

the system freezes.

2017-04-19 01:04 UTC, jarun commented
I think the code is by the book and still it's failing. I am noticing in multiple places that writing from vfs is a bad idea. Reverting this.

2017-04-19 15:56 UTC, cedriczirtacic commented
Did you deleted line 189? In that case the module will crash with vfs_write().

2017-04-19 15:57 UTC, cedriczirtacic commented
Yeah, is not recommended but is one of the few easy ways of writing physical data to disk from kernel space.

2017-04-19 16:12 UTC, jarun commented
> Did you deleted line 189? In that case the module will crash with vfs_write().

Not at all! I tried the changes and bam! I did some debugging but couldn't figure out the root cause other than the fact that the vfs_write() itself goes gaga...

I am expecting more people would face this as well.

Just for reference, it's still possible to read/copy the debugfs file during shutdown:
https://opensource.com/life/16/11/running-commands-shutdown-linux
a little roundabout, but safe.

2017-04-19 16:18 UTC, cedriczirtacic commented
Yes, I know is possible to manipulate the content from the debugfs file and copy the content to an actual file inside a vfs but I wanted to do it directly.

I'm using a Debian using kernel 4.0.6 amd64 and it works. Will keep testing and playing 👍 
Thanks!

2017-04-19 16:20 UTC, jarun commented
Ubuntu 16.04 here (use [Voyager](https://voyagerlive.org/))

```
$ uname -a
Linux tux 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```